// This could be autogenerated
local base = import "base.jsonnet";
local data = import "data.jsonnet";
local encoders = import "encoders.jsonnet";
local multilingual = import "multilingual.jsonnet";

{
  dev: {
    aida_xlmr: multilingual.dev.xlmr_mixed_ml_true_dev +
    base.Name("xlmr_gold") +
    {
      eval_path: "",
      preds_file: "",
    },

    aida_spb: multilingual.dev.spb_on_en_true_dev +
    base.Name("spanbert_gold") + {
      eval_path: "",
      preds_file: "",
    }
  }
}